---
- name: ensure pip.conf file is present in home directory
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.config/pip/pip.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - '[install]'
    - 'user=1'
  when: pip3_install is defined and user is defined
- name: install pip3 packages for root
  pip:
    name: "{{ pip3_install }}"
    executable: pip3
  when: pip3_install is defined and user is not defined
- name: install pip3 packages for user "{{ user }}"
  become: yes
  become_user: "{{ user }}"
  pip:
    executable: pip3
    name: "{{ pip3_install }}"
    extra_args: --user
  when: pip3_install is defined and user is defined
